import React from 'react'
import { jsPDF } from "jspdf";
const Salary = (props) => {
    
     function generatePDF(salary, employee) {
        console.log(employee)
        // var doc = new jsPDF();
        const doc = new jsPDF()
        // console.log(employee)
    
        // doc.setFont("times");
        // // doc.setFontType("bold");
        doc.setFontSize(16);
        doc.text('International Institue of Information Technology, Bangalore', 30, 10);
    
    
        doc.text('---------------------------------------------------------------------------------------------------', 10, 20);
        doc.setFontSize(13);
        // //doc.setFontType('normal');
        doc.setFont("times")
        doc.text('Employee Name ', 20, 40);
        doc.text(employee.first_name, 80,40);
        doc.text(employee.last_name,95,40)
        doc.text('Email_id ',20,50);
        doc.text(employee.email, 80,50);
        doc.text('Title ', 20,60);
        doc.text(employee.title, 80,60);
        doc.text('Date ', 20,70);
        doc.text(salary.payment_date, 80,70);
        doc.text('Amount ', 20,80);
        doc.text(salary.amount.toString(), 80,80);
        doc.text('Description ', 20,90);
        doc.text(salary.description, 80,90);
        doc.text('---------------------------------------------------------------------------------------------------', 20,100);
        doc.text('This is an autogenerated PDF therefore does not require any signature', 20,110);
    
        doc.save('iitb_emp_salary.pdf'); 
    }
    return (
        <tr>
          <td>{props.salary.payment_date}</td>
          <td>{props.salary.amount}</td>
          <td>{props.salary.description}</td>
          <td><button onClick={() => generatePDF(props.salary, props.employee)}>Download</button></td>
        </tr>
      )
}

export default Salary;


